import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Link from 'next/link';

export default function Home() {

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Modulo de Logistica
        </h1>

        <p className={styles.description}>
          Get started by editing{' '}
          <code className={styles.code}>pages/index.js</code>
        </p>

        <div className={styles.card}>
        <h2>Modulo de Logistica</h2>
        <Link href="/RegisterTransportistForm">
        <button type="button" className={styles.button}>Registrar Transportista</button>
        </Link>

        <Link href="/QueryTransportistForm">
        <button type="button" className={styles.button}>Consultar Transportistas</button>
        </Link>
        </div>
        <div className={styles.card}>
        <h2>Modulo de Logistica 2</h2>
        <Link href="/RegisterTransportForm">
        <button type="button" className={styles.button}>Registrar Transporte</button>
        </Link>

        <Link href="/QueryTransportForm">
        <button type="button" className={styles.button}>Consultar Transporte</button>
        </Link>
        </div>

        <div className={styles.card}>
        <h2>Modulo de Logistica 3</h2>
        <Link href="/RegisterUbicationForm">
        <button type="button" className={styles.button}>Registrar Ubicación</button>
        </Link>

        <Link href="/QueryUbicationForm">
        <button type="button" className={styles.button}>Consultar Ubicacion</button>
        </Link>
        </div>

        <div className={styles.card}>
        <h2>Modulo de Logistica 4</h2>
        <Link href="/RegisterRoutesForm">
        <button type="button" className={styles.button}>Registrar Rutas</button>
        </Link>

        <Link href="/QueryRoutesForm">
        <button type="button" className={styles.button}>Consultar Rutas</button>
        </Link>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
